# Site settings
title: mais um site sobre
subtitle: estatísticas e outras coisas
email: arthurlustosaa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  um site sobre estatísticas, tutorias e coisas outras. 
baseurl: "/portfolio" # the subpath of your site, e.g. /blog/
url: "https://gileadekelvin.github.io/portfolio/" # the base hostname & protocol for your site
twitter_username: portfolio
github_username:  portfoliio
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
