# Site settings
title: Portfólio - Gileade
subtitle: Blog sobre análise de dados. Diferentes temas e discussões com o intuito de usar a ciência de dados como nova forma de enxergar o mundo a nossa volta.
email: gileadekelvin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog sobre análise de dados. Diferentes temas e discussões com o intuito de usar a ciência de dados como nova forma de enxergar o mundo a nossa volta.
baseurl: "/portfolio/" # the subpath of your site, e.g. /blog/
url: "https://gileadekelvin.github.io/portfolio/" # the base hostname & protocol for your site
twitter_username: gileadekelvin
github_username:  gileadekelvin
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
